version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jradtilbrook"
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    reviewers:
      - "jradtilbrook"
