language: go

go:
  - 1.11.x
  - '1.12'

script:
  - '[ -z "$(go fmt $(go list ./...))" ]'
  - go vet $(go list ./...)
  - go test $(go list ./...)

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

notifications:
  email:
    on_success: change
    on_failure: always
