steps:
  - label: ":golangci-lint: lint"
    key: lint
    command : golangci-lint run --timeout 2m0s
    agents:
      queue: "hosted"
    plugins:
      - docker#v5.9.0:
          image: "golangci/golangci-lint:v1.54.1"
          always-pull: true
          volumes:
            - "/.cache/golangci-lint/v1.54.1:/root/.cache"

  - label: vet
    key: vet
    command: "make vet"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: docs
    key: docs
    command: .buildkite/steps/documentation.sh
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go
        mount-buildkite-agent: true

  - label: test
    key: test
    command: "make test"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: acceptance tests
    key: testacc
    concurrency: 1
    concurrency_group: terraform-provider-acceptance-tests
    command: .buildkite/steps/annotate.sh
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-terraform-provider-buildkite-main
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_ORGANIZATION_SLUG: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_organization
            BUILDKITE_API_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_api_token
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_analytics_token
      - docker-compose#v3.9.0:
          run: go
          mount-buildkite-agent: "true"
      - test-collector#v1.8.0:
          files: junit-*.xml
          format: junit

  - label: build
    command: "make build-snapshot"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go
    depends_on:
      - lint
      - test
      - testacc
      - vet
      - docs
