steps:
  - label: release
    command: ".buildkite/steps/release.sh"
    plugins:
      - ecr#v2.3.0:
          account-ids: "445615400570"
          login: true
      - docker-compose#v2.2.0:
          run: go
    agents:
      queue: "deploy"
