steps:
  - label: ":golangci-lint: lint"
    key: lint
    agents:
      queue: "hosted"
    plugins:
      - golangci-lint#v1.0.0:
          config: .golangci.yaml

  - label: vet
    key: vet
    command: "make vet"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: docs
    key: docs
    command: .buildkite/steps/documentation.sh
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go
        mount-buildkite-agent: true

  - label: test
    key: test
    command: "make test"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: acceptance tests
    key: testacc
    concurrency: 1
    concurrency_group: terraform-provider-acceptance-tests
    command: .buildkite/steps/annotate.sh
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-terraform-provider-buildkite-main
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_ORGANIZATION_SLUG: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_organization
            BUILDKITE_API_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_api_token
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_analytics_token
      - docker-compose#v3.9.0:
          run: go
          mount-buildkite-agent: "true"
      - test-collector#v1.8.0:
          files: junit-*.xml
          format: junit

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.0:
          variables:
            GITHUB_TOKEN: SCORECARD_TOKEN
      - ossf-scorecard#v1.0.0:
          github_token: $$GITHUB_TOKEN

  - label: build
    command: "make build-snapshot"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v3.9.0:
        run: go
    depends_on:
      - lint
      - test
      - testacc
      - vet
      - docs
