steps:
  - label: release
    command: ".buildkite/steps/release.sh"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-terraform-provider-buildkite-release
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - ecr#v2.3.0:
          account-ids: "445615400570"
          login: true
      - aws-ssm#v1.1.0:
          parameters:
            GITHUB_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-release/github-token
            GPG_SECRET_KEY_BASE64: /pipelines/buildkite/terraform-provider-buildkite-release/gpg-secret-key-base64
      - docker-compose#v5.12.1:
          run: go
    agents:
      queue: "oss-deploy"
