steps:
  - label: ":golangci-lint: lint"
    key: lint
    command : golangci-lint run --timeout 2m0s
    agents:
      queue: "hosted"
    plugins:
      - docker#v5.13.0:
          image: "golangci/golangci-lint:v2.0.2"
          always-pull: true
          volumes:
            - "/.cache/golangci-lint/v2.0.2:/root/.cache"

  - label: vet
    key: vet
    command: "make vet"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v5.12.1:
        run: go

  - label: docs
    key: docs
    command: .buildkite/steps/documentation.sh
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v5.12.1:
        run: go
        mount-buildkite-agent: true

  - label: test
    key: test
    command: "make test"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v5.12.1:
        run: go

  - label: acceptance tests
    key: testacc
    concurrency: 1
    concurrency_group: terraform-provider-acceptance-tests
    command: .buildkite/steps/annotate.sh
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-terraform-provider-buildkite-main
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.1.0:
          parameters:
            BUILDKITE_ORGANIZATION_SLUG: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_organization
            BUILDKITE_API_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_api_token
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_analytics_token
            GITHUB_TEST_REPO: /pipelines/buildkite/terraform-provider-buildkite-main/github_test_repo
            GITHUB_TEST_REPO_ALT: /pipelines/buildkite/terraform-provider-buildkite-main/github_test_repo_alt
      - docker-compose#v5.12.1:
          run: go
          mount-buildkite-agent: "true"
      - test-collector#v1.11.0:
          files: junit-*.xml
          format: junit
    retry:
      automatic:
        - exit_status: -1
          limit: 2

  - label: "Security Scan"
    key: security_scan
    secrets:
      GITHUB_TOKEN: SCORECARD_TOKEN
    plugins:
      - ossf-scorecard#v1.0.1:
          github_token: $$GITHUB_TOKEN
    retry:
      automatic:
        - exit_status: "*"
          limit: 2

  - label: build
    command: "make build-snapshot"
    agents:
      queue: "hosted"
    plugins:
      docker-compose#v5.12.1:
        run: go
    depends_on:
      - lint
      - test
      - testacc
      - vet
      - docs
