steps:
  - label: fmt
    key: fmt
    command: "make testfmt"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: vet
    key: vet
    command: "make vet"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: test
    key: test
    command: "make test"
    plugins:
      docker-compose#v3.9.0:
        run: go

  - label: acceptance tests
    key: testacc
    concurrency: 1
    concurrency_group: terraform-provider-acceptance-tests
    command: .buildkite/steps/annotate.sh
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-terraform-provider-buildkite-main
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_ORGANIZATION_SLUG: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_organization
            BUILDKITE_API_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_api_token
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/terraform-provider-buildkite-main/buildkite_analytics_token
      - docker-compose#v3.9.0:
          run: go
          mount-buildkite-agent: "true"
      - test-collector#v1.8.0:
          files: junit-*.xml
          format: junit

  - label: build
    command: "make"
    plugins:
      docker-compose#v3.9.0:
        run: go
    depends_on:
      - fmt
      - test
      - testacc
      - testacc-nonadmin
      - vet
