// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package buildkite

import (
	"github.com/Khan/genqlient/graphql"
)

// The roles a user can be within a team
type GTeamMemberRole string

const (
	// The user is a regular member of the team
	GTeamMemberRoleMember GTeamMemberRole = "MEMBER"
	// The user can manage pipelines and users within the team
	GTeamMemberRoleMaintainer GTeamMemberRole = "MAINTAINER"
)

// Whether a team is visible or secret within an organization
type GenqlientTeamPrivacy string

const (
	// Visible to all members of the organization
	GenqlientTeamPrivacyVisible GenqlientTeamPrivacy = "VISIBLE"
	// Visible to organization administrators and members
	GenqlientTeamPrivacySecret GenqlientTeamPrivacy = "SECRET"
)

// The access levels that can be assigned to a pipeline
type PipelineAccessLevels string

const (
	// Allows edits, builds and reads
	PipelineAccessLevelsManageBuildAndRead PipelineAccessLevels = "MANAGE_BUILD_AND_READ"
	// Allows builds and read only
	PipelineAccessLevelsBuildAndRead PipelineAccessLevels = "BUILD_AND_READ"
	// Read only - no builds or edits
	PipelineAccessLevelsReadOnly PipelineAccessLevels = "READ_ONLY"
)

// Repository information for a pipeline
type PipelineRepositoryInput struct {
	// Repository information for a pipeline
	Url string `json:"url"`
}

// GetUrl returns PipelineRepositoryInput.Url, and is useful for accessing the field via an interface.
func (v *PipelineRepositoryInput) GetUrl() string { return v.Url }

// Step definition for a pipeline
type PipelineStepsInput struct {
	// Step definition for a pipeline
	Yaml string `json:"yaml"`
}

// GetYaml returns PipelineStepsInput.Yaml, and is useful for accessing the field via an interface.
func (v *PipelineStepsInput) GetYaml() string { return v.Yaml }

// Tag associated with a pipeline
type PipelineTagInput struct {
	// Tag associated with a pipeline
	Label string `json:"label"`
}

// GetLabel returns PipelineTagInput.Label, and is useful for accessing the field via an interface.
func (v *PipelineTagInput) GetLabel() string { return v.Label }

// Autogenerated input type of PipelineUpdate
type PipelineUpdateInput struct {
	// Autogenerated input type of PipelineUpdate
	ClientMutationId string `json:"clientMutationId"`
	// Autogenerated input type of PipelineUpdate
	Id string `json:"id"`
	// Autogenerated input type of PipelineUpdate
	Name string `json:"name"`
	// Autogenerated input type of PipelineUpdate
	Description string `json:"description"`
	// Autogenerated input type of PipelineUpdate
	Emoji string `json:"emoji"`
	// Autogenerated input type of PipelineUpdate
	Color string `json:"color"`
	// Autogenerated input type of PipelineUpdate
	Visibility PipelineVisibility `json:"visibility,omitempty"`
	// Autogenerated input type of PipelineUpdate
	Repository PipelineRepositoryInput `json:"repository"`
	// Autogenerated input type of PipelineUpdate
	Steps PipelineStepsInput `json:"steps"`
	// Autogenerated input type of PipelineUpdate
	DefaultBranch string `json:"defaultBranch"`
	// Autogenerated input type of PipelineUpdate
	NextBuildNumber int `json:"nextBuildNumber,omitempty"`
	// Autogenerated input type of PipelineUpdate
	SkipIntermediateBuilds bool `json:"skipIntermediateBuilds"`
	// Autogenerated input type of PipelineUpdate
	SkipIntermediateBuildsBranchFilter string `json:"skipIntermediateBuildsBranchFilter"`
	// Autogenerated input type of PipelineUpdate
	CancelIntermediateBuilds bool `json:"cancelIntermediateBuilds"`
	// Autogenerated input type of PipelineUpdate
	CancelIntermediateBuildsBranchFilter string `json:"cancelIntermediateBuildsBranchFilter"`
	// Autogenerated input type of PipelineUpdate
	AllowRebuilds bool `json:"allowRebuilds"`
	// Autogenerated input type of PipelineUpdate
	DefaultTimeoutInMinutes int `json:"defaultTimeoutInMinutes"`
	// Autogenerated input type of PipelineUpdate
	MaximumTimeoutInMinutes int `json:"maximumTimeoutInMinutes"`
	// Autogenerated input type of PipelineUpdate
	ClusterId *string `json:"clusterId,omitempty"`
	// Autogenerated input type of PipelineUpdate
	Archived bool `json:"archived,omitempty"`
	// Autogenerated input type of PipelineUpdate
	Tags []PipelineTagInput `json:"tags"`
	// Autogenerated input type of PipelineUpdate
	BranchConfiguration string `json:"branchConfiguration"`
}

// GetClientMutationId returns PipelineUpdateInput.ClientMutationId, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetClientMutationId() string { return v.ClientMutationId }

// GetId returns PipelineUpdateInput.Id, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetId() string { return v.Id }

// GetName returns PipelineUpdateInput.Name, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetName() string { return v.Name }

// GetDescription returns PipelineUpdateInput.Description, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetDescription() string { return v.Description }

// GetEmoji returns PipelineUpdateInput.Emoji, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetEmoji() string { return v.Emoji }

// GetColor returns PipelineUpdateInput.Color, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetColor() string { return v.Color }

// GetVisibility returns PipelineUpdateInput.Visibility, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetVisibility() PipelineVisibility { return v.Visibility }

// GetRepository returns PipelineUpdateInput.Repository, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetRepository() PipelineRepositoryInput { return v.Repository }

// GetSteps returns PipelineUpdateInput.Steps, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetSteps() PipelineStepsInput { return v.Steps }

// GetDefaultBranch returns PipelineUpdateInput.DefaultBranch, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetDefaultBranch() string { return v.DefaultBranch }

// GetNextBuildNumber returns PipelineUpdateInput.NextBuildNumber, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetNextBuildNumber() int { return v.NextBuildNumber }

// GetSkipIntermediateBuilds returns PipelineUpdateInput.SkipIntermediateBuilds, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetSkipIntermediateBuilds() bool { return v.SkipIntermediateBuilds }

// GetSkipIntermediateBuildsBranchFilter returns PipelineUpdateInput.SkipIntermediateBuildsBranchFilter, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetSkipIntermediateBuildsBranchFilter() string {
	return v.SkipIntermediateBuildsBranchFilter
}

// GetCancelIntermediateBuilds returns PipelineUpdateInput.CancelIntermediateBuilds, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetCancelIntermediateBuilds() bool { return v.CancelIntermediateBuilds }

// GetCancelIntermediateBuildsBranchFilter returns PipelineUpdateInput.CancelIntermediateBuildsBranchFilter, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetCancelIntermediateBuildsBranchFilter() string {
	return v.CancelIntermediateBuildsBranchFilter
}

// GetAllowRebuilds returns PipelineUpdateInput.AllowRebuilds, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetAllowRebuilds() bool { return v.AllowRebuilds }

// GetDefaultTimeoutInMinutes returns PipelineUpdateInput.DefaultTimeoutInMinutes, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetDefaultTimeoutInMinutes() int { return v.DefaultTimeoutInMinutes }

// GetMaximumTimeoutInMinutes returns PipelineUpdateInput.MaximumTimeoutInMinutes, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetMaximumTimeoutInMinutes() int { return v.MaximumTimeoutInMinutes }

// GetClusterId returns PipelineUpdateInput.ClusterId, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetClusterId() *string { return v.ClusterId }

// GetArchived returns PipelineUpdateInput.Archived, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetArchived() bool { return v.Archived }

// GetTags returns PipelineUpdateInput.Tags, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetTags() []PipelineTagInput { return v.Tags }

// GetBranchConfiguration returns PipelineUpdateInput.BranchConfiguration, and is useful for accessing the field via an interface.
func (v *PipelineUpdateInput) GetBranchConfiguration() string { return v.BranchConfiguration }

// The visibility of the pipeline
type PipelineVisibility string

const (
	// The pipeline is public
	PipelineVisibilityPublic PipelineVisibility = "PUBLIC"
	// The pipeline is private
	PipelineVisibilityPrivate PipelineVisibility = "PRIVATE"
)

// The roles a user can be within a team
type TeamMemberRole string

const (
	// The user is a regular member of the team
	TeamMemberRoleMember TeamMemberRole = "MEMBER"
	// The user can manage pipelines and users within the team
	TeamMemberRoleMaintainer TeamMemberRole = "MAINTAINER"
)

// Whether a team is visible or secret within an organization
type TeamPrivacy string

const (
	// Visible to all members of the organization
	TeamPrivacyVisible TeamPrivacy = "VISIBLE"
	// Visible to organization administrators and members
	TeamPrivacySecret TeamPrivacy = "SECRET"
)

// __createAgentTokenInput is used internally by genqlient
type __createAgentTokenInput struct {
	OrganizationId string `json:"organizationId"`
	Description    string `json:"description"`
}

// GetOrganizationId returns __createAgentTokenInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__createAgentTokenInput) GetOrganizationId() string { return v.OrganizationId }

// GetDescription returns __createAgentTokenInput.Description, and is useful for accessing the field via an interface.
func (v *__createAgentTokenInput) GetDescription() string { return v.Description }

// __getAgentTokenInput is used internally by genqlient
type __getAgentTokenInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __getAgentTokenInput.Slug, and is useful for accessing the field via an interface.
func (v *__getAgentTokenInput) GetSlug() string { return v.Slug }

// __getOrganizationInput is used internally by genqlient
type __getOrganizationInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __getOrganizationInput.Slug, and is useful for accessing the field via an interface.
func (v *__getOrganizationInput) GetSlug() string { return v.Slug }

// __getPipelineInput is used internally by genqlient
type __getPipelineInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __getPipelineInput.Slug, and is useful for accessing the field via an interface.
func (v *__getPipelineInput) GetSlug() string { return v.Slug }

// __getTeamInput is used internally by genqlient
type __getTeamInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __getTeamInput.Slug, and is useful for accessing the field via an interface.
func (v *__getTeamInput) GetSlug() string { return v.Slug }

// __revokeAgentTokenInput is used internally by genqlient
type __revokeAgentTokenInput struct {
	Id     string `json:"id"`
	Reason string `json:"reason"`
}

// GetId returns __revokeAgentTokenInput.Id, and is useful for accessing the field via an interface.
func (v *__revokeAgentTokenInput) GetId() string { return v.Id }

// GetReason returns __revokeAgentTokenInput.Reason, and is useful for accessing the field via an interface.
func (v *__revokeAgentTokenInput) GetReason() string { return v.Reason }

// __setApiIpAddressesInput is used internally by genqlient
type __setApiIpAddressesInput struct {
	OrganizationID string `json:"organizationID"`
	IpAddresses    string `json:"ipAddresses"`
}

// GetOrganizationID returns __setApiIpAddressesInput.OrganizationID, and is useful for accessing the field via an interface.
func (v *__setApiIpAddressesInput) GetOrganizationID() string { return v.OrganizationID }

// GetIpAddresses returns __setApiIpAddressesInput.IpAddresses, and is useful for accessing the field via an interface.
func (v *__setApiIpAddressesInput) GetIpAddresses() string { return v.IpAddresses }

// __updatePipelineInput is used internally by genqlient
type __updatePipelineInput struct {
	Input PipelineUpdateInput `json:"input"`
}

// GetInput returns __updatePipelineInput.Input, and is useful for accessing the field via an interface.
func (v *__updatePipelineInput) GetInput() PipelineUpdateInput { return v.Input }

// createAgentTokenAgentTokenCreateAgentTokenCreatePayload includes the requested fields of the GraphQL type AgentTokenCreatePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of AgentTokenCreate.
type createAgentTokenAgentTokenCreateAgentTokenCreatePayload struct {
	// The token value used to register a new agent. Please ensure to securely copy this value immediately upon generation as it will not be displayed again.
	TokenValue     string                                                                `json:"tokenValue"`
	AgentTokenEdge createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdge `json:"agentTokenEdge"`
}

// GetTokenValue returns createAgentTokenAgentTokenCreateAgentTokenCreatePayload.TokenValue, and is useful for accessing the field via an interface.
func (v *createAgentTokenAgentTokenCreateAgentTokenCreatePayload) GetTokenValue() string {
	return v.TokenValue
}

// GetAgentTokenEdge returns createAgentTokenAgentTokenCreateAgentTokenCreatePayload.AgentTokenEdge, and is useful for accessing the field via an interface.
func (v *createAgentTokenAgentTokenCreateAgentTokenCreatePayload) GetAgentTokenEdge() createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdge {
	return v.AgentTokenEdge
}

// createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdge includes the requested fields of the GraphQL type AgentTokenEdge.
type createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdge struct {
	Node createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken `json:"node"`
}

// GetNode returns createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdge.Node, and is useful for accessing the field via an interface.
func (v *createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdge) GetNode() createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken {
	return v.Node
}

// createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken includes the requested fields of the GraphQL type AgentToken.
// The GraphQL type's documentation follows.
//
// A token used to connect an agent to Buildkite
type createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken struct {
	Id string `json:"id"`
	// A description about what this agent token is used for
	Description string `json:"description"`
	// The public UUID for the agent
	Uuid string `json:"uuid"`
}

// GetId returns createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken.Id, and is useful for accessing the field via an interface.
func (v *createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken) GetId() string {
	return v.Id
}

// GetDescription returns createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken.Description, and is useful for accessing the field via an interface.
func (v *createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken) GetDescription() string {
	return v.Description
}

// GetUuid returns createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken.Uuid, and is useful for accessing the field via an interface.
func (v *createAgentTokenAgentTokenCreateAgentTokenCreatePayloadAgentTokenEdgeNodeAgentToken) GetUuid() string {
	return v.Uuid
}

// createAgentTokenResponse is returned by createAgentToken on success.
type createAgentTokenResponse struct {
	// Create a new agent registration token.
	AgentTokenCreate createAgentTokenAgentTokenCreateAgentTokenCreatePayload `json:"agentTokenCreate"`
}

// GetAgentTokenCreate returns createAgentTokenResponse.AgentTokenCreate, and is useful for accessing the field via an interface.
func (v *createAgentTokenResponse) GetAgentTokenCreate() createAgentTokenAgentTokenCreateAgentTokenCreatePayload {
	return v.AgentTokenCreate
}

// getAgentTokenAgentToken includes the requested fields of the GraphQL type AgentToken.
// The GraphQL type's documentation follows.
//
// A token used to connect an agent to Buildkite
type getAgentTokenAgentToken struct {
	Id string `json:"id"`
	// A description about what this agent token is used for
	Description string `json:"description"`
	// The public UUID for the agent
	Uuid string `json:"uuid"`
}

// GetId returns getAgentTokenAgentToken.Id, and is useful for accessing the field via an interface.
func (v *getAgentTokenAgentToken) GetId() string { return v.Id }

// GetDescription returns getAgentTokenAgentToken.Description, and is useful for accessing the field via an interface.
func (v *getAgentTokenAgentToken) GetDescription() string { return v.Description }

// GetUuid returns getAgentTokenAgentToken.Uuid, and is useful for accessing the field via an interface.
func (v *getAgentTokenAgentToken) GetUuid() string { return v.Uuid }

// getAgentTokenResponse is returned by getAgentToken on success.
type getAgentTokenResponse struct {
	// Find an agent token by its slug
	AgentToken getAgentTokenAgentToken `json:"agentToken"`
}

// GetAgentToken returns getAgentTokenResponse.AgentToken, and is useful for accessing the field via an interface.
func (v *getAgentTokenResponse) GetAgentToken() getAgentTokenAgentToken { return v.AgentToken }

// getOrganizationOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An organization
type getOrganizationOrganization struct {
	// A space-separated allowlist of IP addresses that can access the organization via the GraphQL or REST API
	AllowedApiIpAddresses string `json:"allowedApiIpAddresses"`
	Id                    string `json:"id"`
	// The public UUID for this organization
	Uuid string `json:"uuid"`
}

// GetAllowedApiIpAddresses returns getOrganizationOrganization.AllowedApiIpAddresses, and is useful for accessing the field via an interface.
func (v *getOrganizationOrganization) GetAllowedApiIpAddresses() string {
	return v.AllowedApiIpAddresses
}

// GetId returns getOrganizationOrganization.Id, and is useful for accessing the field via an interface.
func (v *getOrganizationOrganization) GetId() string { return v.Id }

// GetUuid returns getOrganizationOrganization.Uuid, and is useful for accessing the field via an interface.
func (v *getOrganizationOrganization) GetUuid() string { return v.Uuid }

// getOrganizationResponse is returned by getOrganization on success.
type getOrganizationResponse struct {
	// Find an organization
	Organization getOrganizationOrganization `json:"organization"`
}

// GetOrganization returns getOrganizationResponse.Organization, and is useful for accessing the field via an interface.
func (v *getOrganizationResponse) GetOrganization() getOrganizationOrganization {
	return v.Organization
}

// getPipelinePipeline includes the requested fields of the GraphQL type Pipeline.
// The GraphQL type's documentation follows.
//
// A pipeline
type getPipelinePipeline struct {
	Id string `json:"id"`
	// The default branch for this pipeline
	DefaultBranch string `json:"defaultBranch"`
	// The short description of the pipeline
	Description string `json:"description"`
	// The name of the pipeline
	Name string `json:"name"`
	// The repository for this pipeline
	Repository getPipelinePipelineRepository `json:"repository"`
	// The slug of the pipeline
	Slug string `json:"slug"`
	// The URL to use in your repository settings for commit webhooks
	WebhookURL string `json:"webhookURL"`
}

// GetId returns getPipelinePipeline.Id, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetId() string { return v.Id }

// GetDefaultBranch returns getPipelinePipeline.DefaultBranch, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetDefaultBranch() string { return v.DefaultBranch }

// GetDescription returns getPipelinePipeline.Description, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetDescription() string { return v.Description }

// GetName returns getPipelinePipeline.Name, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetName() string { return v.Name }

// GetRepository returns getPipelinePipeline.Repository, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetRepository() getPipelinePipelineRepository { return v.Repository }

// GetSlug returns getPipelinePipeline.Slug, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetSlug() string { return v.Slug }

// GetWebhookURL returns getPipelinePipeline.WebhookURL, and is useful for accessing the field via an interface.
func (v *getPipelinePipeline) GetWebhookURL() string { return v.WebhookURL }

// getPipelinePipelineRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository associated with a pipeline
type getPipelinePipelineRepository struct {
	// The git URL for this repository
	Url string `json:"url"`
}

// GetUrl returns getPipelinePipelineRepository.Url, and is useful for accessing the field via an interface.
func (v *getPipelinePipelineRepository) GetUrl() string { return v.Url }

// getPipelineResponse is returned by getPipeline on success.
type getPipelineResponse struct {
	// Find a pipeline
	Pipeline getPipelinePipeline `json:"pipeline"`
}

// GetPipeline returns getPipelineResponse.Pipeline, and is useful for accessing the field via an interface.
func (v *getPipelineResponse) GetPipeline() getPipelinePipeline { return v.Pipeline }

// getTeamResponse is returned by getTeam on success.
type getTeamResponse struct {
	// Find a team
	Team getTeamTeam `json:"team"`
}

// GetTeam returns getTeamResponse.Team, and is useful for accessing the field via an interface.
func (v *getTeamResponse) GetTeam() getTeamTeam { return v.Team }

// getTeamTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organization team
type getTeamTeam struct {
	// New organization members will be granted this role on this team
	DefaultMemberRole GTeamMemberRole `json:"defaultMemberRole"`
	// A description of the team
	Description string `json:"description"`
	Id          string `json:"id"`
	// Add new organization members to this team by default
	IsDefaultTeam bool `json:"isDefaultTeam"`
	// Whether or not team members can create new pipelines in this team
	MembersCanCreatePipelines bool `json:"membersCanCreatePipelines"`
	// The name of the team
	Name string `json:"name"`
	// The privacy setting for this team
	Privacy GenqlientTeamPrivacy `json:"privacy"`
	// The slug of the team
	Slug string `json:"slug"`
	// The public UUID for this team
	Uuid string `json:"uuid"`
}

// GetDefaultMemberRole returns getTeamTeam.DefaultMemberRole, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetDefaultMemberRole() GTeamMemberRole { return v.DefaultMemberRole }

// GetDescription returns getTeamTeam.Description, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetDescription() string { return v.Description }

// GetId returns getTeamTeam.Id, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetId() string { return v.Id }

// GetIsDefaultTeam returns getTeamTeam.IsDefaultTeam, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetIsDefaultTeam() bool { return v.IsDefaultTeam }

// GetMembersCanCreatePipelines returns getTeamTeam.MembersCanCreatePipelines, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetMembersCanCreatePipelines() bool { return v.MembersCanCreatePipelines }

// GetName returns getTeamTeam.Name, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetName() string { return v.Name }

// GetPrivacy returns getTeamTeam.Privacy, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetPrivacy() GenqlientTeamPrivacy { return v.Privacy }

// GetSlug returns getTeamTeam.Slug, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetSlug() string { return v.Slug }

// GetUuid returns getTeamTeam.Uuid, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetUuid() string { return v.Uuid }

// revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayload includes the requested fields of the GraphQL type AgentTokenRevokePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of AgentTokenRevoke.
type revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayload struct {
	AgentToken revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken `json:"agentToken"`
}

// GetAgentToken returns revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayload.AgentToken, and is useful for accessing the field via an interface.
func (v *revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayload) GetAgentToken() revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken {
	return v.AgentToken
}

// revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken includes the requested fields of the GraphQL type AgentToken.
// The GraphQL type's documentation follows.
//
// A token used to connect an agent to Buildkite
type revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken struct {
	Id string `json:"id"`
	// A description about what this agent token is used for
	Description string `json:"description"`
	// The public UUID for the agent
	Uuid string `json:"uuid"`
}

// GetId returns revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken.Id, and is useful for accessing the field via an interface.
func (v *revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken) GetId() string {
	return v.Id
}

// GetDescription returns revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken.Description, and is useful for accessing the field via an interface.
func (v *revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken) GetDescription() string {
	return v.Description
}

// GetUuid returns revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken.Uuid, and is useful for accessing the field via an interface.
func (v *revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayloadAgentToken) GetUuid() string {
	return v.Uuid
}

// revokeAgentTokenResponse is returned by revokeAgentToken on success.
type revokeAgentTokenResponse struct {
	// Revoke an agent registration token.
	AgentTokenRevoke revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayload `json:"agentTokenRevoke"`
}

// GetAgentTokenRevoke returns revokeAgentTokenResponse.AgentTokenRevoke, and is useful for accessing the field via an interface.
func (v *revokeAgentTokenResponse) GetAgentTokenRevoke() revokeAgentTokenAgentTokenRevokeAgentTokenRevokePayload {
	return v.AgentTokenRevoke
}

// setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayload includes the requested fields of the GraphQL type OrganizationAPIIPAllowlistUpdateMutationPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of OrganizationAPIIPAllowlistUpdateMutation.
type setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayload struct {
	Organization setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayloadOrganization `json:"organization"`
}

// GetOrganization returns setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayload.Organization, and is useful for accessing the field via an interface.
func (v *setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayload) GetOrganization() setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayloadOrganization {
	return v.Organization
}

// setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayloadOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An organization
type setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayloadOrganization struct {
	// A space-separated allowlist of IP addresses that can access the organization via the GraphQL or REST API
	AllowedApiIpAddresses string `json:"allowedApiIpAddresses"`
}

// GetAllowedApiIpAddresses returns setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayloadOrganization.AllowedApiIpAddresses, and is useful for accessing the field via an interface.
func (v *setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayloadOrganization) GetAllowedApiIpAddresses() string {
	return v.AllowedApiIpAddresses
}

// setApiIpAddressesResponse is returned by setApiIpAddresses on success.
type setApiIpAddressesResponse struct {
	// Sets an allowlist of IP addresses for API access to an organization. Please note that this is a beta feature and is not yet available to all organizations.
	OrganizationApiIpAllowlistUpdate setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayload `json:"organizationApiIpAllowlistUpdate"`
}

// GetOrganizationApiIpAllowlistUpdate returns setApiIpAddressesResponse.OrganizationApiIpAllowlistUpdate, and is useful for accessing the field via an interface.
func (v *setApiIpAddressesResponse) GetOrganizationApiIpAllowlistUpdate() setApiIpAddressesOrganizationApiIpAllowlistUpdateOrganizationAPIIPAllowlistUpdateMutationPayload {
	return v.OrganizationApiIpAllowlistUpdate
}

// updatePipelinePipelineUpdatePipelineUpdatePayload includes the requested fields of the GraphQL type PipelineUpdatePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of PipelineUpdate.
type updatePipelinePipelineUpdatePipelineUpdatePayload struct {
	Pipeline updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline `json:"pipeline"`
}

// GetPipeline returns updatePipelinePipelineUpdatePipelineUpdatePayload.Pipeline, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayload) GetPipeline() updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline {
	return v.Pipeline
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline includes the requested fields of the GraphQL type Pipeline.
// The GraphQL type's documentation follows.
//
// A pipeline
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline struct {
	Id string `json:"id"`
	// Whether existing builds can be rebuilt as new builds.
	AllowRebuilds bool `json:"allowRebuilds"`
	// When a new build is created on a branch, any previous builds that are running on the same branch will be automatically cancelled
	CancelIntermediateBuilds bool `json:"cancelIntermediateBuilds"`
	// Limit which branches build cancelling applies to, for example `!main` will ensure that the main branch won't have it's builds automatically cancelled.
	CancelIntermediateBuildsBranchFilter string                                                           `json:"cancelIntermediateBuildsBranchFilter"`
	Cluster                              updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineCluster `json:"cluster"`
	// The default branch for this pipeline
	DefaultBranch string `json:"defaultBranch"`
	// The default timeout in minutes for all command steps in this pipeline. This can still be overridden in any command step
	DefaultTimeoutInMinutes int `json:"defaultTimeoutInMinutes"`
	// The maximum timeout in minutes for all command steps in this pipeline. Any command step without a timeout or with a timeout greater than this value will be set to this value.
	MaximumTimeoutInMinutes int `json:"maximumTimeoutInMinutes"`
	// The short description of the pipeline
	Description string `json:"description"`
	// The name of the pipeline
	Name string `json:"name"`
	// The repository for this pipeline
	Repository updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineRepository `json:"repository"`
	// When a new build is created on a branch, any previous builds that haven't yet started on the same branch will be automatically marked as skipped.
	SkipIntermediateBuilds bool `json:"skipIntermediateBuilds"`
	// Limit which branches build skipping applies to, for example `!main` will ensure that the main branch won't have it's builds automatically skipped.
	SkipIntermediateBuildsBranchFilter string `json:"skipIntermediateBuildsBranchFilter"`
	// The slug of the pipeline
	Slug  string                                                         `json:"slug"`
	Steps updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineSteps `json:"steps"`
	// Tags that have been given to this pipeline
	Tags []updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTagsPipelineTag `json:"tags"`
	// Teams associated with this pipeline
	Teams updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnection `json:"teams"`
	// The URL to use in your repository settings for commit webhooks
	WebhookURL string `json:"webhookURL"`
}

// GetId returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Id, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetId() string { return v.Id }

// GetAllowRebuilds returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.AllowRebuilds, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetAllowRebuilds() bool {
	return v.AllowRebuilds
}

// GetCancelIntermediateBuilds returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.CancelIntermediateBuilds, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetCancelIntermediateBuilds() bool {
	return v.CancelIntermediateBuilds
}

// GetCancelIntermediateBuildsBranchFilter returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.CancelIntermediateBuildsBranchFilter, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetCancelIntermediateBuildsBranchFilter() string {
	return v.CancelIntermediateBuildsBranchFilter
}

// GetCluster returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Cluster, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetCluster() updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineCluster {
	return v.Cluster
}

// GetDefaultBranch returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.DefaultBranch, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetDefaultBranch() string {
	return v.DefaultBranch
}

// GetDefaultTimeoutInMinutes returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.DefaultTimeoutInMinutes, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetDefaultTimeoutInMinutes() int {
	return v.DefaultTimeoutInMinutes
}

// GetMaximumTimeoutInMinutes returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.MaximumTimeoutInMinutes, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetMaximumTimeoutInMinutes() int {
	return v.MaximumTimeoutInMinutes
}

// GetDescription returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Description, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetDescription() string {
	return v.Description
}

// GetName returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Name, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetName() string { return v.Name }

// GetRepository returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Repository, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetRepository() updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineRepository {
	return v.Repository
}

// GetSkipIntermediateBuilds returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.SkipIntermediateBuilds, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetSkipIntermediateBuilds() bool {
	return v.SkipIntermediateBuilds
}

// GetSkipIntermediateBuildsBranchFilter returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.SkipIntermediateBuildsBranchFilter, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetSkipIntermediateBuildsBranchFilter() string {
	return v.SkipIntermediateBuildsBranchFilter
}

// GetSlug returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Slug, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetSlug() string { return v.Slug }

// GetSteps returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Steps, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetSteps() updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineSteps {
	return v.Steps
}

// GetTags returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Tags, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetTags() []updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTagsPipelineTag {
	return v.Tags
}

// GetTeams returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.Teams, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetTeams() updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnection {
	return v.Teams
}

// GetWebhookURL returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline.WebhookURL, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipeline) GetWebhookURL() string {
	return v.WebhookURL
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineCluster includes the requested fields of the GraphQL type Cluster.
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineCluster struct {
	Id string `json:"id"`
}

// GetId returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineCluster.Id, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineCluster) GetId() string {
	return v.Id
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository associated with a pipeline
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineRepository struct {
	// The git URL for this repository
	Url string `json:"url"`
}

// GetUrl returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineRepository.Url, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineRepository) GetUrl() string {
	return v.Url
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineSteps includes the requested fields of the GraphQL type PipelineSteps.
// The GraphQL type's documentation follows.
//
// Steps defined on a pipeline
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineSteps struct {
	// A YAML representation of the pipeline steps
	Yaml string `json:"yaml"`
}

// GetYaml returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineSteps.Yaml, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineSteps) GetYaml() string {
	return v.Yaml
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTagsPipelineTag includes the requested fields of the GraphQL type PipelineTag.
// The GraphQL type's documentation follows.
//
// A tag associated with a pipeline
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTagsPipelineTag struct {
	// The label for this tag
	Label string `json:"label"`
}

// GetLabel returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTagsPipelineTag.Label, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTagsPipelineTag) GetLabel() string {
	return v.Label
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnection includes the requested fields of the GraphQL type TeamPipelineConnection.
// The GraphQL type's documentation follows.
//
// A collection of TeamPipeline records
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnection struct {
	Edges []updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdge `json:"edges"`
}

// GetEdges returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnection.Edges, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnection) GetEdges() []updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdge {
	return v.Edges
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdge includes the requested fields of the GraphQL type TeamPipelineEdge.
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdge struct {
	Node updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline `json:"node"`
}

// GetNode returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdge.Node, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdge) GetNode() updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline {
	return v.Node
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline includes the requested fields of the GraphQL type TeamPipeline.
// The GraphQL type's documentation follows.
//
// An pipeline that's been assigned to a team
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline struct {
	// The access level users have to this pipeline
	AccessLevel PipelineAccessLevels `json:"accessLevel"`
	Id          string               `json:"id"`
	// The team associated with this team member
	Team updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam `json:"team"`
}

// GetAccessLevel returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline.AccessLevel, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline) GetAccessLevel() PipelineAccessLevels {
	return v.AccessLevel
}

// GetId returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline.Id, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline) GetId() string {
	return v.Id
}

// GetTeam returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline.Team, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipeline) GetTeam() updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam {
	return v.Team
}

// updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organization team
type updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam struct {
	// A description of the team
	Description string `json:"description"`
	Id          string `json:"id"`
	// Add new organization members to this team by default
	IsDefaultTeam bool `json:"isDefaultTeam"`
	// New organization members will be granted this role on this team
	DefaultMemberRole TeamMemberRole `json:"defaultMemberRole"`
	// The name of the team
	Name string `json:"name"`
	// Whether or not team members can create new pipelines in this team
	MembersCanCreatePipelines bool `json:"membersCanCreatePipelines"`
	// The privacy setting for this team
	Privacy TeamPrivacy `json:"privacy"`
	// The slug of the team
	Slug string `json:"slug"`
	// The public UUID for this team
	Uuid string `json:"uuid"`
}

// GetDescription returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.Description, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetDescription() string {
	return v.Description
}

// GetId returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.Id, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetId() string {
	return v.Id
}

// GetIsDefaultTeam returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.IsDefaultTeam, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetIsDefaultTeam() bool {
	return v.IsDefaultTeam
}

// GetDefaultMemberRole returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.DefaultMemberRole, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetDefaultMemberRole() TeamMemberRole {
	return v.DefaultMemberRole
}

// GetName returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.Name, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetName() string {
	return v.Name
}

// GetMembersCanCreatePipelines returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.MembersCanCreatePipelines, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetMembersCanCreatePipelines() bool {
	return v.MembersCanCreatePipelines
}

// GetPrivacy returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.Privacy, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetPrivacy() TeamPrivacy {
	return v.Privacy
}

// GetSlug returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.Slug, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetSlug() string {
	return v.Slug
}

// GetUuid returns updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam.Uuid, and is useful for accessing the field via an interface.
func (v *updatePipelinePipelineUpdatePipelineUpdatePayloadPipelineTeamsTeamPipelineConnectionEdgesTeamPipelineEdgeNodeTeamPipelineTeam) GetUuid() string {
	return v.Uuid
}

// updatePipelineResponse is returned by updatePipeline on success.
type updatePipelineResponse struct {
	// Change the settings for a pipeline.
	PipelineUpdate updatePipelinePipelineUpdatePipelineUpdatePayload `json:"pipelineUpdate"`
}

// GetPipelineUpdate returns updatePipelineResponse.PipelineUpdate, and is useful for accessing the field via an interface.
func (v *updatePipelineResponse) GetPipelineUpdate() updatePipelinePipelineUpdatePipelineUpdatePayload {
	return v.PipelineUpdate
}

// The query or mutation executed by createAgentToken.
const createAgentToken_Operation = `
mutation createAgentToken ($organizationId: ID!, $description: String) {
	agentTokenCreate(input: {organizationID:$organizationId,description:$description}) {
		tokenValue
		agentTokenEdge {
			node {
				id
				description
				uuid
			}
		}
	}
}
`

func createAgentToken(
	client graphql.Client,
	organizationId string,
	description string,
) (*createAgentTokenResponse, error) {
	req := &graphql.Request{
		OpName: "createAgentToken",
		Query:  createAgentToken_Operation,
		Variables: &__createAgentTokenInput{
			OrganizationId: organizationId,
			Description:    description,
		},
	}
	var err error

	var data createAgentTokenResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getAgentToken.
const getAgentToken_Operation = `
query getAgentToken ($slug: ID!) {
	agentToken(slug: $slug) {
		id
		description
		uuid
	}
}
`

func getAgentToken(
	client graphql.Client,
	slug string,
) (*getAgentTokenResponse, error) {
	req := &graphql.Request{
		OpName: "getAgentToken",
		Query:  getAgentToken_Operation,
		Variables: &__getAgentTokenInput{
			Slug: slug,
		},
	}
	var err error

	var data getAgentTokenResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getOrganization.
const getOrganization_Operation = `
query getOrganization ($slug: ID!) {
	organization(slug: $slug) {
		allowedApiIpAddresses
		id
		uuid
	}
}
`

func getOrganization(
	client graphql.Client,
	slug string,
) (*getOrganizationResponse, error) {
	req := &graphql.Request{
		OpName: "getOrganization",
		Query:  getOrganization_Operation,
		Variables: &__getOrganizationInput{
			Slug: slug,
		},
	}
	var err error

	var data getOrganizationResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getPipeline.
const getPipeline_Operation = `
query getPipeline ($slug: ID!) {
	pipeline(slug: $slug) {
		id
		defaultBranch
		description
		name
		repository {
			url
		}
		slug
		webhookURL
	}
}
`

func getPipeline(
	client graphql.Client,
	slug string,
) (*getPipelineResponse, error) {
	req := &graphql.Request{
		OpName: "getPipeline",
		Query:  getPipeline_Operation,
		Variables: &__getPipelineInput{
			Slug: slug,
		},
	}
	var err error

	var data getPipelineResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getTeam.
const getTeam_Operation = `
query getTeam ($slug: ID!) {
	team(slug: $slug) {
		defaultMemberRole
		description
		id
		isDefaultTeam
		membersCanCreatePipelines
		name
		privacy
		slug
		uuid
	}
}
`

func getTeam(
	client graphql.Client,
	slug string,
) (*getTeamResponse, error) {
	req := &graphql.Request{
		OpName: "getTeam",
		Query:  getTeam_Operation,
		Variables: &__getTeamInput{
			Slug: slug,
		},
	}
	var err error

	var data getTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by revokeAgentToken.
const revokeAgentToken_Operation = `
mutation revokeAgentToken ($id: ID!, $reason: String!) {
	agentTokenRevoke(input: {id:$id,reason:$reason}) {
		agentToken {
			id
			description
			uuid
		}
	}
}
`

func revokeAgentToken(
	client graphql.Client,
	id string,
	reason string,
) (*revokeAgentTokenResponse, error) {
	req := &graphql.Request{
		OpName: "revokeAgentToken",
		Query:  revokeAgentToken_Operation,
		Variables: &__revokeAgentTokenInput{
			Id:     id,
			Reason: reason,
		},
	}
	var err error

	var data revokeAgentTokenResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by setApiIpAddresses.
const setApiIpAddresses_Operation = `
mutation setApiIpAddresses ($organizationID: ID!, $ipAddresses: String!) {
	organizationApiIpAllowlistUpdate(input: {organizationID:$organizationID,ipAddresses:$ipAddresses}) {
		organization {
			allowedApiIpAddresses
		}
	}
}
`

func setApiIpAddresses(
	client graphql.Client,
	organizationID string,
	ipAddresses string,
) (*setApiIpAddressesResponse, error) {
	req := &graphql.Request{
		OpName: "setApiIpAddresses",
		Query:  setApiIpAddresses_Operation,
		Variables: &__setApiIpAddressesInput{
			OrganizationID: organizationID,
			IpAddresses:    ipAddresses,
		},
	}
	var err error

	var data setApiIpAddressesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by updatePipeline.
const updatePipeline_Operation = `
mutation updatePipeline ($input: PipelineUpdateInput!) {
	pipelineUpdate(input: $input) {
		pipeline {
			id
			allowRebuilds
			cancelIntermediateBuilds
			cancelIntermediateBuildsBranchFilter
			cluster {
				id
			}
			defaultBranch
			defaultTimeoutInMinutes
			maximumTimeoutInMinutes
			description
			name
			repository {
				url
			}
			skipIntermediateBuilds
			skipIntermediateBuildsBranchFilter
			slug
			steps {
				yaml
			}
			tags {
				label
			}
			teams(first: 50) {
				edges {
					node {
						accessLevel
						id
						team {
							description
							id
							isDefaultTeam
							defaultMemberRole
							name
							membersCanCreatePipelines
							privacy
							slug
							uuid
						}
					}
				}
			}
			webhookURL
		}
	}
}
`

func updatePipeline(
	client graphql.Client,
	input PipelineUpdateInput,
) (*updatePipelineResponse, error) {
	req := &graphql.Request{
		OpName: "updatePipeline",
		Query:  updatePipeline_Operation,
		Variables: &__updatePipelineInput{
			Input: input,
		},
	}
	var err error

	var data updatePipelineResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}
