// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"github.com/Khan/genqlient/graphql"
)

// GetTeamResponse is returned by GetTeam on success.
type GetTeamResponse struct {
	// Find a team by its UUID
	Team GetTeamTeam `json:"team"`
}

// GetTeam returns GetTeamResponse.Team, and is useful for accessing the field via an interface.
func (v *GetTeamResponse) GetTeam() GetTeamTeam { return v.Team }

// GetTeamTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organization team
type GetTeamTeam struct {
	// New organization members will be granted this role on this team
	DefaultMemberRole TeamMemberRole `json:"defaultMemberRole"`
	// A description of the team
	Description string `json:"description"`
	Id          string `json:"id"`
	// Add new organization members to this team by default
	IsDefaultTeam bool `json:"isDefaultTeam"`
	// Whether or not team members can create new pipelines in this team
	MembersCanCreatePipelines bool `json:"membersCanCreatePipelines"`
	// The name of the team
	Name string `json:"name"`
	// The privacy setting for this team
	Privacy TeamPrivacy `json:"privacy"`
	// The slug of the team
	Slug string `json:"slug"`
	// The public UUID for this team
	Uuid string `json:"uuid"`
}

// GetDefaultMemberRole returns GetTeamTeam.DefaultMemberRole, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetDefaultMemberRole() TeamMemberRole { return v.DefaultMemberRole }

// GetDescription returns GetTeamTeam.Description, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetDescription() string { return v.Description }

// GetId returns GetTeamTeam.Id, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetId() string { return v.Id }

// GetIsDefaultTeam returns GetTeamTeam.IsDefaultTeam, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetIsDefaultTeam() bool { return v.IsDefaultTeam }

// GetMembersCanCreatePipelines returns GetTeamTeam.MembersCanCreatePipelines, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetMembersCanCreatePipelines() bool { return v.MembersCanCreatePipelines }

// GetName returns GetTeamTeam.Name, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetName() string { return v.Name }

// GetPrivacy returns GetTeamTeam.Privacy, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetPrivacy() TeamPrivacy { return v.Privacy }

// GetSlug returns GetTeamTeam.Slug, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetSlug() string { return v.Slug }

// GetUuid returns GetTeamTeam.Uuid, and is useful for accessing the field via an interface.
func (v *GetTeamTeam) GetUuid() string { return v.Uuid }

// The roles a user can be within a team
type TeamMemberRole string

const (
	// The user is a regular member of the team
	TeamMemberRoleMember TeamMemberRole = "MEMBER"
	// The user can manage pipelines and users within the team
	TeamMemberRoleMaintainer TeamMemberRole = "MAINTAINER"
)

// Whether a team is visible or secret within an organization
type TeamPrivacy string

const (
	// Visible to all members of the organization
	TeamPrivacyVisible TeamPrivacy = "VISIBLE"
	// Visible to organization administrators and members
	TeamPrivacySecret TeamPrivacy = "SECRET"
)

// __GetTeamInput is used internally by genqlient
type __GetTeamInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __GetTeamInput.Slug, and is useful for accessing the field via an interface.
func (v *__GetTeamInput) GetSlug() string { return v.Slug }

func GetTeam(
	client graphql.Client,
	slug string,
) (*GetTeamResponse, error) {
	__input := __GetTeamInput{
		Slug: slug,
	}
	var err error

	var retval GetTeamResponse
	err = client.MakeRequest(
		nil,
		"GetTeam",
		`
query GetTeam ($slug: ID!) {
	team(slug: $slug) {
		defaultMemberRole
		description
		id
		isDefaultTeam
		membersCanCreatePipelines
		name
		privacy
		slug
		uuid
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}
