query getNode(
    $id: ID!
) {
    node(id: $id){
        ... on Pipeline {
            ...PipelineFields
        }
        ... on PipelineTemplate {
            ...PipelineTemplateFields
        }
        ... on Rule {
            ...OrganizationRuleFields
        }
        ... on TeamMember {
            ...TeamMemberFields
        }
        ... on Team {
            ...TeamFields
        }
        ... on TeamSuite {
            ...TeamSuiteFields
        }
        ... on TeamRegistry {
            ...TeamRegistryFields
        }
        ... on TeamPipeline {
            ... TeamPipelineFields
        }
        ... on Cluster {
            ... ClusterFields
        }
    }
}

query getPipelineByNode($id: ID!) {
    node(id: $id) {
        ... on Pipeline {
            ...PipelineFields
        }
    }
}

query getOrganizationRuleByNode($id: ID!) {
    node(id: $id) {
        ... on Rule {
            ...OrganizationRuleFields
        }
    }
}

query getTeamByNode($id: ID!) {
    node(id: $id) {
        ... on Team {
            ...TeamFields
        }
    }
}

query getTeamPipelineByNode($id: ID!) {
    node(id: $id) {
        ... on TeamPipeline {
            ...TeamPipelineFields
        }
    }
}

query getClusterByNode($id: ID!) {
    node(id: $id) {
        ... on Cluster {
            ...ClusterFields
        }
    }
}
