query GetOrganizationMembers(
    $slug: ID!,
    # @genqlient(pointer: true)
    $cursor: String,
    # @genqlient(pointer: true, omitempty: true)
    $team: TeamSelector,
    # @genqlient(omitempty: true)
    $role: [OrganizationMemberRole!],
) {
    organization(slug: $slug) {
        id
        members(first: 500, after: $cursor, team: $team, role: $role) {
            pageInfo {
                endCursor
                hasNextPage
            }
            edges {
                node {
                    user {
                        id
                        uuid
                        name
                        email
                    }
                }
            }
        }
    }
}
