fragment TeamMemberFields on TeamMember {
    id
    uuid
    team {
        id
    }
    user {
        id
    }
    role 
}

mutation createTeamMember(
    $teamID: ID!, 
    $userID: ID!,
    # @genqlient(omitempty: true)
    $role: TeamMemberRole,
) {
    teamMemberCreate(
        input: {
            teamID: $teamID
            userID: $userID,
            role: $role,
        }
    ) {
        teamMemberEdge {
            node {
                ...TeamMemberFields
            }
        }
    }
}

mutation updateTeamMember(
    $id: ID!,
    $role: TeamMemberRole!
) {
    teamMemberUpdate(
        input: {
            id: $id
            role: $role
        }
    ) {
        teamMember {
            ...TeamMemberFields
        }
    }
}

mutation deleteTeamMember(
    $id: ID!
) {
    teamMemberDelete(
        input: {
            id: $id
        }
    ) {
        clientMutationId
    }
}
query getTeamMemberIdByEmail(
    $slug: ID!,
    $email: String!,
    # @genqlient(pointer: true)
    $cursor: String
) {
    organization(slug: $slug) {
        id
        members(first: 1, email: $email) {
            edges {
                node {
                    teams(first: 50, after: $cursor) {
                        pageInfo {
                            endCursor
                            hasNextPage
                        }
                        edges {
                            node {
                                id
                                team {
                                    slug
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
