#!/bin/bash -eu

TERRAFORM_VERSION="0.14.11"

echo "+++ downloading terraform ${TERRAFORM_VERSION}"

curl -o /usr/local/bin/terraform --silent "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
chmod +x /usr/local/bin/terraform

